name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4.4.0
      with:
        java-version: '17'

    - name: Cache Gradle packages
      uses: actions/cache@v4.1.2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build APK (Debug)
      run: ./gradlew assembleDebug

    - name: Read version from file
      id: read_version
      run: |
        VERSION=$(cat version.txt)
        echo "::set-output name=VERSION::$VERSION"

    - name: Create a new tag
      id: create_tag
      run: |
        VERSION=${{ steps.read_version.outputs.VERSION }}
        git tag "v$VERSION"
        git push origin "v$VERSION"
        echo "::set-output name=TAG::v$VERSION"

    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.create_tag.outputs.TAG }}
        release_name: "APK Build v${{ steps.create_tag.outputs.TAG }}"
        body: "This is an automatically generated release containing the debug APK for version ${{ steps.create_tag.outputs.TAG }}."
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload APK to GitHub release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_tag.outputs.TAG }}
        asset_path: app/build/outputs/apk/debug/dexApp-DEBUG-$VERSION.apk
        asset_name: dexApp-DEBUG-$VERSION.apk
        asset_content_type: application/vnd.android.package-archive
